// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkiogvffcejdltfktrci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFraW9ndmZmY2VqZGx0Zmt0cmNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzQ2MzksImV4cCI6MjA2ODk1MDYzOX0.LWlRBPRmM1ZNW2BgdkopSjy31jgBOk3DrbWSDUz9_a0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});